### ISSUE TITLE
LESS API proposals than the extension wants

### ISSUE THREAD

**Issue by wanfuse123** [faaydemir/openai-powered-snippets#2]
faaydemir.openaipoweredsnippet
note I should have 8000 token access now

2023-05-11 09:38:02.186 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-05-11 09:38:02.683 [error] Extension 'github.copilot-nightly' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, terminalDataWriteEvent
product.json (WINS): inlineCompletionsAdditions
2023-05-11 09:38:02.690 [warning] [KarelNagel.gpt3]: Cannot register 'gpt3.apiKey'. This property is already registered.
2023-05-11 09:38:04.397 [error] [Extension Host] Error: ENOENT: no such file or directory, lstat '/home/top/ALL_COMPRESSION_ALGO/.vscode/openaisnipets.js'
    at lstatSync (node:fs:1566:3)
    at Object.t.lstatSync (node:electron/js2c/asar_bundle:2:3729)
    at importSnippets (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:82764)
    at e.activate (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:391339)
    at Function.eb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14705)
    at Function.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14409)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:12432
    at v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6644)
    at v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6607)
    at v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6064)
2023-05-11 09:38:04.397 [error] [Extension Host] Error: ENOENT: no such file or directory, lstat '/home/top/ALL_COMPRESSION_ALGO/.vscode/openaisnipets.json'
    at lstatSync (node:fs:1566:3)
    at Object.t.lstatSync (node:electron/js2c/asar_bundle:2:3729)
    at importSnippets (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:82764)
    at e.activate (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:391339)
    at Function.eb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14705)
    at Function.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14409)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:12432
    at v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6644)
    at v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6607)
    at v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6064)
2023-05-11 09:38:04.397 [error] [Extension Host] Error: ENOENT: no such file or directory, lstat '/home/top/ALL_COMPRESSION_ALGO/.vscode/openaisnipets.yaml'
    at lstatSync (node:fs:1566:3)
    at Object.t.lstatSync (node:electron/js2c/asar_bundle:2:3729)
    at importSnippets (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:82764)
    at e.activate (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:391339)
    at Function.eb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14705)
    at Function.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14409)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:12432
    at v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6644)
    at v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6607)
    at v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6064)
2023-05-11 09:38:05.344 [info] [perf] Render performance baseline is 28ms

how do I fix this issue?

**Comment by faaydemir** [comment]
hi, there are logs for several issues 3 of them related to repo. these are:

> 2023-05-11 09:38:04.397 [error] [Extension Host] Error: ENOENT: no such file or directory, lstat '/home/top/ALL_COMPRESSION_ALGO/.vscode/openaisnipets.js'
at lstatSync (node:fs:1566:3)
at Object.t.lstatSync (node:electron/js2c/asar_bundle:2:3729)
at importSnippets (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:82764)
at e.activate (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:391339)
at Function.eb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14705)
at Function.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14409)
at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:12432
at v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6644)
at v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6607)
at v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6064)
2023-05-11 09:38:04.397 [error] [Extension Host] Error: ENOENT: no such file or directory, lstat '/home/top/ALL_COMPRESSION_ALGO/.vscode/openaisnipets.json'
at lstatSync (node:fs:1566:3)
at Object.t.lstatSync (node:electron/js2c/asar_bundle:2:3729)
at importSnippets (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:82764)
at e.activate (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:391339)
at Function.eb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14705)
at Function.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14409)
at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:12432
at v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6644)
at v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6607)
at v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6064)
2023-05-11 09:38:04.397 [error] [Extension Host] Error: ENOENT: no such file or directory, lstat '/home/top/ALL_COMPRESSION_ALGO/.vscode/openaisnipets.yaml'
at lstatSync (node:fs:1566:3)
at Object.t.lstatSync (node:electron/js2c/asar_bundle:2:3729)
at importSnippets (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:82764)
at e.activate (/home/top/.vscode/extensions/faaydemir.openaipoweredsnippet-0.0.22/dist/extension.js:2:391339)
at Function.eb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14705)
at Function.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:14409)
at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:12432
at v.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6644)
at v.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6607)
at v.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:6064)
2023-05-11 09:38:05.344 [info] [perf] Render performance baseline is 28ms

this extension expects users to define template prompts files in yaml,json, or js format. prompt template paths can be set via extension settings, but by defult it searches template files under the {projectpath}/.vscode folder. if there is no file in .vscode folder just write logs. yes this not looks like a good practice it can be a warning/info with a less scary log message, but this should not break extension. 
I will fix it in the next versions.

**Comment by faaydemir** [comment]
#6 resolve issue.
